services:

  web:
    container_name: drink-water-web
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - '.:/app'
    # command: gunicorn core.wsgi:application --timeout 0 --bind 0.0.0.0:5001 --log-level=INFO --reload
    command: poetry run python manage.py runserver 0.0.0.0:5001
