# Generated by Django 4.2.14 on 2024-08-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=50)),
                ("weight", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserDataHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("weight", models.FloatField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="drink_water.user")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("action", models.CharField(db_index=True, default="DRINK WATER", max_length=30)),
                ("quantity", models.FloatField()),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="drink_water.user")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
